# Generated by Django 4.0.1 on 2022-01-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlide',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=350)),
                ('image', models.ImageField(default='', upload_to='media/')),
            ],
        ),
    ]
