# Generated by Django 4.0.1 on 2022-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='imageslide',
            name='image',
            field=models.ImageField(default='', upload_to='slide/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hdimage1',
            field=models.ImageField(default='', upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hdimage2',
            field=models.ImageField(default='', upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hdimage3',
            field=models.ImageField(default='', upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hdimage4',
            field=models.ImageField(default='', upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='smallimage',
            field=models.ImageField(default='', upload_to='product/'),
        ),
    ]
