# Generated by Django 4.0.1 on 2022-01-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_product_slug_alter_imageslide_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arifmobile',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='product',
            name='arifwhatspp',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='product',
            name='danishmobile',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='product',
            name='danishwhatspp',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
