# Generated by Django 4.0.1 on 2022-02-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arifmobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='arifwhatspp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='danishmobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='danishwhatspp',
            field=models.IntegerField(default=0),
        ),
    ]
