# Generated by Django 4.0.1 on 2022-02-01 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_product_arifmobile_alter_product_arifwhatspp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cat',
            field=models.CharField(choices=[('Almiras', 'Almiras'), ('LCD Panels', 'LCD Panels'), ('Modular Kitchens', 'Modular Kitchens'), ('Beds', 'Beds'), ('Tables', 'Tables'), ('Showroom Works', 'Showroom Works'), ('Doors', 'Doors'), ('Palles', 'Palles')], default='', max_length=400),
        ),
        migrations.AddField(
            model_name='product',
            name='update',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
