# Generated by Django 3.2.5 on 2021-10-25 10:11

import OnlineExamination.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the define format', regex='^\\+?1?\\d{9,12}$')])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=OnlineExamination.models.upload_image, width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('stream', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
