# Generated by Django 3.2.5 on 2021-10-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExamination', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
